import Footer from "@/components/layout-components/Footer";
import "./globals.css";

import Header from "@/components/layout-components/Header";
import { OverPassFont } from "@/fonts";
import ReduxStoreProvider from "@/lib/redux/ReduxStoreProvider";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "CSCInfoNest",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxStoreProvider>
        <body
          className={`${OverPassFont.className}`}
        >
          <Toaster position="top-right" />
          <Header />
          {children}
          <Footer />
        </body>
      </ReduxStoreProvider>
    </html>
  );
}
